# 服务器端口
server:
    port: 8080

# 数据库连接配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    redis:
        host: chaifanggui.cn
        port: 6379
        password: Loveluoluo521
        database: 1
        